# Generated by Django 6.0.6 on 2026-06-11 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBlood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('last_donated', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('units_available', models.PositiveBigIntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_blood', to='blood.donorprofile')),
            ],
        ),
    ]
