# Generated by Django 6.0.6 on 2026-06-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_availableblood'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='available_blood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='blood.availableblood'),
        ),
    ]
