# Generated by Django 6.0.6 on 2026-06-14 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_donationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('want_to_donate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donorprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_offer', to='blood.bloodrequest')),
            ],
        ),
    ]
