# Generated by Django 6.0.6 on 2026-06-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_donationoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationoffer',
            name='want_to_donate',
        ),
        migrations.AddField(
            model_name='donationoffer',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default='offered', max_length=20),
        ),
    ]
